[package]
name = 'rtiktoken'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rtiktoken'

[dependencies]
extendr-api = { version = "0.7.1", default-features = false, features = ["result_list"] }
tiktoken-rs = "0.5.9"
